# Generated by Django 3.2 on 2021-04-30 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportocrats', '0002_auto_20210430_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cricket_Female',
            fields=[
                ('cricket_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.player_male')),
                ('team_no', models.IntegerField()),
                ('result', models.CharField(max_length=40)),
                ('performance', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Player_Female',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('DOB', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField()),
            ],
        ),
    ]
